# Form implementation generated from reading ui file '.\application_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import json

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPixmap

from Members import Member
import euroavia_db


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 180, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 230, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 380, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 430, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 330, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 280, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.AcWo_checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.AcWo_checkBox.setGeometry(QtCore.QRect(550, 230, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        self.AcWo_checkBox.setFont(font)
        self.AcWo_checkBox.setStyleSheet("QCheckBox {\n"
"    font: 700 14pt \"Segoe UI\";\n"
"    color: white; \n"
"}\n"
"")
        self.AcWo_checkBox.setText("AirCraft Workshop")
        self.AcWo_checkBox.setObjectName("AcWo_checkBox")
        self.NUME_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.NUME_lineEdit.setGeometry(QtCore.QRect(100, 170, 121, 31))
        self.NUME_lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid gray; /* Schimbă gray cu culoarea dorită */\n"
"    border-radius: 10px; /* Schimbă 10px cu raza dorită */\n"
"    padding: 5px; /* Schimbă 5px cu spațierea dorită */\n"
"}")
        self.NUME_lineEdit.setObjectName("NUME_lineEdit")
        self.PRENUME_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.PRENUME_lineEdit.setGeometry(QtCore.QRect(140, 220, 121, 31))
        self.PRENUME_lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid gray; /* Schimbă gray cu culoarea dorită */\n"
"    border-radius: 10px; /* Schimbă 10px cu raza dorită */\n"
"    padding: 5px; /* Schimbă 5px cu spațierea dorită */\n"
"}")
        self.PRENUME_lineEdit.setObjectName("PRENUME_lineEdit")
        self.PRENUME_2_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.PRENUME_2_lineEdit.setGeometry(QtCore.QRect(150, 270, 121, 31))
        self.PRENUME_2_lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid gray; /* Schimbă gray cu culoarea dorită */\n"
"    border-radius: 10px; /* Schimbă 10px cu raza dorită */\n"
"    padding: 5px; /* Schimbă 5px cu spațierea dorită */\n"
"}")
        self.PRENUME_2_lineEdit.setObjectName("PRENUME_2_lineEdit")
        self.NUMAR_DE_TELEFON_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.NUMAR_DE_TELEFON_lineEdit.setGeometry(QtCore.QRect(230, 320, 141, 31))
        self.NUMAR_DE_TELEFON_lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid gray; /* Schimbă gray cu culoarea dorită */\n"
"    border-radius: 10px; /* Schimbă 10px cu raza dorită */\n"
"    padding: 5px; /* Schimbă 5px cu spațierea dorită */\n"
"}")
        self.NUMAR_DE_TELEFON_lineEdit.setObjectName("NUMAR_DE_TELEFON_lineEdit")
        self.AN_DE_STUDIU_comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.AN_DE_STUDIU_comboBox.setGeometry(QtCore.QRect(170, 380, 61, 31))
        self.AN_DE_STUDIU_comboBox.setStyleSheet("QComboBox {\n"
"    border: 2px solid gray; /* Schimbă gray cu culoarea dorită */\n"
"    border-radius: 10px; /* Schimbă 10px cu raza dorită */\n"
"    padding: 5px; /* Schimbă 5px cu spațierea dorită */\n"
"    background: white; /* Schimbă white cu culoarea de fundal dorită */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px; /* Schimbă 15px cu lățimea dorită pentru săgeata dropdown */\n"
"    border: none; /* Elimină bordura din jurul săgeții dropdown */\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(down_arrow.png); /* Asigură-te că ai o imagine pentru săgeata dropdown */\n"
"    width: 10px; /* Schimbă 10px cu dimensiunea dorită */\n"
"    height: 10px; /* Schimbă 10px cu dimensiunea dorită */\n"
"}")
        self.AN_DE_STUDIU_comboBox.setObjectName("AN_DE_STUDIU_comboBox")
        self.AN_DE_STUDIU_comboBox.addItem("")
        self.AN_DE_STUDIU_comboBox.addItem("")
        self.AN_DE_STUDIU_comboBox.addItem("")
        self.AN_DE_STUDIU_comboBox.addItem("")
        self.FACULTATE_comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.FACULTATE_comboBox.setGeometry(QtCore.QRect(140, 420, 221, 31))
        self.FACULTATE_comboBox.setStyleSheet("QComboBox {\n"
"    border: 2px solid gray; /* Schimbă gray cu culoarea dorită */\n"
"    border-radius: 10px; /* Schimbă 10px cu raza dorită */\n"
"    padding: 5px; /* Schimbă 5px cu spațierea dorită */\n"
"    background: white; /* Schimbă white cu culoarea de fundal dorită */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px; /* Schimbă 15px cu lățimea dorită pentru săgeata dropdown */\n"
"    border: none; /* Elimină bordura din jurul săgeții dropdown */\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(down_arrow.png); /* Asigură-te că ai o imagine pentru săgeata dropdown */\n"
"    width: 10px; /* Schimbă 10px cu dimensiunea dorită */\n"
"    height: 10px; /* Schimbă 10px cu dimensiunea dorită */\n"
"}")
        self.FACULTATE_comboBox.setObjectName("FACULTATE_comboBox")
        self.FACULTATE_comboBox.addItem("")
        self.FACULTATE_comboBox.addItem("")
        self.FACULTATE_comboBox.addItem("")
        self.FACULTATE_comboBox.addItem("")
        self.FACULTATE_comboBox.addItem("")
        self.FACULTATE_comboBox.addItem("")
        self.FACULTATE_comboBox.addItem("")
        self.FACULTATE_comboBox.addItem("")
        self.FACULTATE_comboBox.addItem("")
        self.FACULTATE_comboBox.addItem("")
        self.FACULTATE_comboBox.addItem("")
        self.FACULTATE_comboBox.addItem("")
        self.FACULTATE_comboBox.addItem("")
        self.FACULTATE_comboBox.addItem("")
        self.FACULTATE_comboBox.addItem("")
        self.DroWo_checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.DroWo_checkBox.setGeometry(QtCore.QRect(410, 340, 171, 20))
        self.DroWo_checkBox.setStyleSheet("QCheckBox {\n"
"    font: 700 14pt \"Segoe UI\";\n"
"    color: white; \n"
"}\n"
"")
        self.DroWo_checkBox.setObjectName("DroWo_checkBox")
        self.RoWo_checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.RoWo_checkBox.setGeometry(QtCore.QRect(600, 380, 161, 20))
        self.RoWo_checkBox.setStyleSheet("QCheckBox {\n"
"    font: 700 14pt \"Segoe UI\";\n"
"    color: white; \n"
"}\n"
"")
        self.RoWo_checkBox.setObjectName("RoWo_checkBox")
        self.HSS_checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.HSS_checkBox.setGeometry(QtCore.QRect(400, 270, 191, 20))
        self.HSS_checkBox.setStyleSheet("QCheckBox {\n"
"    font: 700 14pt \"Segoe UI\";\n"
"    color: white; \n"
"}\n"
"")
        self.HSS_checkBox.setObjectName("HSS_checkBox")
        self.WiCa_checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.WiCa_checkBox.setGeometry(QtCore.QRect(600, 310, 141, 20))
        self.WiCa_checkBox.setStyleSheet("QCheckBox {\n"
"    font: 700 14pt \"Segoe UI\";\n"
"    color: white; \n"
"}\n"
"")
        self.WiCa_checkBox.setObjectName("WiCa_checkBox")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(330, 180, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 480, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.DEPARTAMENT_comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.DEPARTAMENT_comboBox.setGeometry(QtCore.QRect(180, 470, 71, 31))
        self.DEPARTAMENT_comboBox.setStyleSheet("QComboBox {\n"
"    border: 2px solid gray; /* Schimbă gray cu culoarea dorită */\n"
"    border-radius: 10px; /* Schimbă 10px cu raza dorită */\n"
"    padding: 5px; /* Schimbă 5px cu spațierea dorită */\n"
"    background: white; /* Schimbă white cu culoarea de fundal dorită */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px; /* Schimbă 15px cu lățimea dorită pentru săgeata dropdown */\n"
"    border: none; /* Elimină bordura din jurul săgeții dropdown */\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(down_arrow.png); /* Asigură-te că ai o imagine pentru săgeata dropdown */\n"
"    width: 10px; /* Schimbă 10px cu dimensiunea dorită */\n"
"    height: 10px; /* Schimbă 10px cu dimensiunea dorită */\n"
"}\n"
"\n"
"")
        self.DEPARTAMENT_comboBox.setObjectName("DEPARTAMENT_comboBox")
        self.DEPARTAMENT_comboBox.addItem("")
        self.DEPARTAMENT_comboBox.addItem("")
        self.DEPARTAMENT_comboBox.addItem("")
        self.DEPARTAMENT_comboBox.addItem("")
        self.DEPARTAMENT_comboBox.addItem("")
        self.label_9_LOGO = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9_LOGO.setGeometry(QtCore.QRect(560, 350, 251, 251))
        self.label_9_LOGO.setText("")
        self.label_9_LOGO.setPixmap(QtGui.QPixmap(":/newPrefix/EUROAVIA_Logo.png"))
        self.label_9_LOGO.setScaledContents(True)
        self.label_9_LOGO.setObjectName("label_9_LOGO")
        self.label_BACKGROUND = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_BACKGROUND.setGeometry(QtCore.QRect(-20, -10, 831, 591))
        self.label_BACKGROUND.setObjectName("label_BACKGROUND")
        self.label_upb_logo = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_upb_logo.setGeometry(QtCore.QRect(450, 20, 341, 131))
        self.label_upb_logo.setText("")
        self.label_upb_logo.setPixmap(QtGui.QPixmap(":/newPrefix/1643641029799.png"))
        self.label_upb_logo.setScaledContents(True)
        self.label_upb_logo.setObjectName("label_upb_logo")
        self.label_plane_logo = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_plane_logo.setGeometry(QtCore.QRect(10, 20, 171, 141))
        self.label_plane_logo.setText("")
        self.label_plane_logo.setPixmap(QtGui.QPixmap(":/newPrefix/plane-semi-flat-b2d996.webp"))
        self.label_plane_logo.setScaledContents(True)
        self.label_plane_logo.setObjectName("label_plane_logo")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(280, 50, 271, 61))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(310, 110, 201, 31))
        self.label_12.setObjectName("label_12")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(390, 460, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius: 15px; /* Valoarea aceasta o poți ajusta pentru a obține rotunjimea dorită */\n"
"    border: 2px solid #ADD8E6; /* Bordura butonului */\n"
"    background-color:#ADD8E6; /* Culoarea de fundal a butonului */\n"
"    color: white; /* Culoarea textului */\n"
"    padding: 5px; /* Spațierea internă */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #87CEEB; /* Culoarea de fundal când mouse-ul este deasupra butonului */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #5FA9D0; /* Culoarea de fundal când butonul este apăsat */\n"
"    border: 2px solid #5FA9D0; /* Bordura butonului când este apăsat */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_BACKGROUND.raise_()
        self.label_9_LOGO.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.AcWo_checkBox.raise_()
        self.NUME_lineEdit.raise_()
        self.PRENUME_lineEdit.raise_()
        self.PRENUME_2_lineEdit.raise_()
        self.NUMAR_DE_TELEFON_lineEdit.raise_()
        self.AN_DE_STUDIU_comboBox.raise_()
        self.FACULTATE_comboBox.raise_()
        self.DroWo_checkBox.raise_()
        self.RoWo_checkBox.raise_()
        self.HSS_checkBox.raise_()
        self.WiCa_checkBox.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.DEPARTAMENT_comboBox.raise_()
        self.label_upb_logo.raise_()
        self.label_plane_logo.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700; color:#ffffff;\">NUME:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700; color:#ffffff;\">PRENUME:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700; color:#ffffff;\">AN DE STUDIU:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700; color:#ffffff;\">FACULTATE:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700; color:#ffffff;\">NUMAR DE TELEFON:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700; color:#ffffff;\">PRENUME 2:</span></p></body></html>"))
        self.AN_DE_STUDIU_comboBox.setItemText(0, _translate("MainWindow", "I"))
        self.AN_DE_STUDIU_comboBox.setItemText(1, _translate("MainWindow", "II"))
        self.AN_DE_STUDIU_comboBox.setItemText(2, _translate("MainWindow", "III"))
        self.AN_DE_STUDIU_comboBox.setItemText(3, _translate("MainWindow", "IV"))
        self.FACULTATE_comboBox.setItemText(0, _translate("MainWindow", "Facultatea de Inginerie Electrică"))
        self.FACULTATE_comboBox.setItemText(1, _translate("MainWindow", "Facultatea de Energetică"))
        self.FACULTATE_comboBox.setItemText(2, _translate("MainWindow", "Facultatea de Automatică și Calculatoare"))
        self.FACULTATE_comboBox.setItemText(3, _translate("MainWindow", "Facultatea de Electronică, Telecomunicații și Tehnologia Informației"))
        self.FACULTATE_comboBox.setItemText(4, _translate("MainWindow", "Facultatea de Inginerie Mecanică și Mecatronică"))
        self.FACULTATE_comboBox.setItemText(5, _translate("MainWindow", "Facultatea de Inginerie Industrială și Robotică"))
        self.FACULTATE_comboBox.setItemText(6, _translate("MainWindow", "Facultatea de Ingineria Sistemelor Biotehnice"))
        self.FACULTATE_comboBox.setItemText(7, _translate("MainWindow", "Facultatea de Transporturi"))
        self.FACULTATE_comboBox.setItemText(8, _translate("MainWindow", "Facultatea de Inginerie Aerospațială"))
        self.FACULTATE_comboBox.setItemText(9, _translate("MainWindow", "Facultatea de Știința și Ingineria Materialelor"))
        self.FACULTATE_comboBox.setItemText(10, _translate("MainWindow", "Facultatea de Inginerie Chimică și Biotehnologii"))
        self.FACULTATE_comboBox.setItemText(11, _translate("MainWindow", "Facultatea de Inginerie în Limbi Străine"))
        self.FACULTATE_comboBox.setItemText(12, _translate("MainWindow", "Facultatea de Științe Aplicate"))
        self.FACULTATE_comboBox.setItemText(13, _translate("MainWindow", "Facultatea de Inginerie Medicală"))
        self.FACULTATE_comboBox.setItemText(14, _translate("MainWindow", "Facultatea de Antreprenoriat, Ingineria și Managementul Afacerilor"))
        self.DroWo_checkBox.setText(_translate("MainWindow", "Drone Workshop"))
        self.RoWo_checkBox.setText(_translate("MainWindow", "Rocket Workshop"))
        self.HSS_checkBox.setText(_translate("MainWindow", "Head Start Session"))
        self.WiCa_checkBox.setText(_translate("MainWindow", "Winter Camp"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700; color:#ffffff;\">LA CE EVENIMENTE VEI PARTICIPA?</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700; color:#ffffff;\">DEPARTAMENT:</span></p></body></html>"))
        self.DEPARTAMENT_comboBox.setItemText(0, _translate("MainWindow", "IT"))
        self.DEPARTAMENT_comboBox.setItemText(1, _translate("MainWindow", "MARKETING"))
        self.DEPARTAMENT_comboBox.setItemText(2, _translate("MainWindow", "LEGAL"))
        self.DEPARTAMENT_comboBox.setItemText(3, _translate("MainWindow", "TEHNIC"))
        self.DEPARTAMENT_comboBox.setItemText(4, _translate("MainWindow", "EVENTS"))
        self.label_BACKGROUND.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/EUROAVIA_Logo.png\"/></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700; text-decoration: underline; color:#ffffff;\">FORMULAR INSCRIERE</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700; color:#ffffff;\">EUROAVIA 2024-2025</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "INSCRIE-TE!"))

        qpixmap = QPixmap("EUROAVIA_Logo.png")
        self.label_BACKGROUND.setPixmap(qpixmap)
        qpixmap = QPixmap("plane-semi-flat-b2d996.webp")
        self.label_plane_logo.setPixmap(qpixmap)
        qpixmap = QPixmap("EUROAVIA_Logo.png")
        self.label_9_LOGO.setPixmap(qpixmap)
        qpixmap = QPixmap("1643641029799.png")
        self.label_upb_logo.setPixmap(qpixmap)
        self.pushButton.clicked.connect(self.add_student)

    def add_student(self):
        events = []
        last_name = self.NUME_lineEdit.text()
        first_name = self.PRENUME_lineEdit.text()
        middle_name = self.PRENUME_2_lineEdit.text()
        telephone_number = self.NUMAR_DE_TELEFON_lineEdit.text()
        study_year = self.AN_DE_STUDIU_comboBox.currentText()
        college = self.FACULTATE_comboBox.currentText()
        department = self.DEPARTAMENT_comboBox.currentText()
        with open("config.json", 'r') as f:
            department_id = json.loads(f.read())['departments_id'][department]
        if self.AcWo_checkBox.isChecked(): events.append(self.AcWo_checkBox.text())
        if self.DroWo_checkBox.isChecked(): events.append(self.DroWo_checkBox.text())
        if self.RoWo_checkBox.isChecked(): events.append(self.RoWo_checkBox.text())
        if self.HSS_checkBox.isChecked(): events.append(self.HSS_checkBox.text())
        if self.WiCa_checkBox.isChecked(): events.append(self.WiCa_checkBox.text())
        member = Member(last_name=last_name,first_name=first_name,
                        middle_name=middle_name,telephone_number=telephone_number,
                        study_year=study_year,college=college,
                        department_id=department_id, events=events)
        euroavia_db.insert_into_db(member = member)
        print("S a executat!")












if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
