# Form implementation generated from reading ui file '.\menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPixmap


class Ui_MenuWindow(object):
    def setupUi(self, MenuWindow):
        MenuWindow.setObjectName("MenuWindow")
        MenuWindow.resize(771, 600)
        app.setWindowIcon(QtGui.QIcon("images/rocket.png"))
        MenuWindow.setMinimumSize(QtCore.QSize(771, 600))
        MenuWindow.setMaximumSize(QtCore.QSize(771, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MenuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.menu_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.menu_label.setGeometry(QtCore.QRect(300, 60, 191, 81))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.menu_label.setFont(font)
        self.menu_label.setObjectName("menu_label")
        self.background_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.background_label.setGeometry(QtCore.QRect(0, -20, 811, 621))
        self.background_label.setObjectName("background_label")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 220, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #4DBB63; /* Background color */\n"
"    border: none; /* Remove default border */\n"
"    color: black; /* Text color */\n"
"    width: 100px; /* Width of the button */\n"
"    height: 100px; /* Height of the button */\n"
"    border-radius: 50px; /* Rounded corners, half of width/height */\n"
"    text-align: center; /* Center text */\n"
"    font-size: 12px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    transition: all 0.2s ease; /* Smooth transition for all properties */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* Darker background on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41; /* Even darker background on press */\n"
"    transform: scale(0.95); /* Slightly shrink button to give visual feedback */\n"
"}")
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.woman_choosing_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.woman_choosing_label.setGeometry(QtCore.QRect(180, 150, 431, 351))
        self.woman_choosing_label.setPixmap(QtGui.QPixmap(":/newPrefix/Desktop/pngtree-woman-making-decision-between-two-options-png-image_6336529.png"))
        self.woman_choosing_label.setScaledContents(True)
        self.woman_choosing_label.setObjectName("woman_choosing_label")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 210, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #FF474C; /* Background color */\n"
"    border: none; /* Remove default border */\n"
"    color: black; /* Text color */\n"
"    width: 100px; /* Width of the button */\n"
"    height: 100px; /* Height of the button */\n"
"    border-radius: 50px; /* Rounded corners, half of width/height */\n"
"    text-align: center; /* Center text */\n"
"    font-size: 12px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    transition: all 0.2s ease; /* Smooth transition for all properties */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FF5F5C; /* Slightly lighter but closer to the original color */\n"
"    transform: scale(1.05); /* Increase size on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FF474A; /* Even darker background on press */\n"
"    transform: scale(0.95); /* Slightly shrink button to give visual feedback */\n"
"}")
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.euroavia_logo_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.euroavia_logo_label.setGeometry(QtCore.QRect(20, 400, 211, 211))
        self.euroavia_logo_label.setText("")
        self.euroavia_logo_label.setPixmap(QtGui.QPixmap(":/newPrefix/EUROAVIA_Logo.png"))
        self.euroavia_logo_label.setScaledContents(True)
        self.euroavia_logo_label.setObjectName("euroavia_logo_label")
        self.plane_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.plane_label.setGeometry(QtCore.QRect(510, 30, 221, 171))
        self.plane_label.setText("")
        self.plane_label.setPixmap(QtGui.QPixmap(":/newPrefix/Desktop/image-removebg-preview.png"))
        self.plane_label.setScaledContents(True)
        self.plane_label.setObjectName("plane_label")
        self.background_label.raise_()
        self.menu_label.raise_()
        self.woman_choosing_label.raise_()
        self.pushButton_2.raise_()
        self.euroavia_logo_label.raise_()
        self.pushButton.raise_()
        self.plane_label.raise_()
        MenuWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MenuWindow)
        QtCore.QMetaObject.connectSlotsByName(MenuWindow)

    def retranslateUi(self, MenuWindow):
        _translate = QtCore.QCoreApplication.translate
        MenuWindow.setWindowTitle(_translate("MenuWindow", "MenuWindow"))
        self.menu_label.setText(_translate("MenuWindow", "<html><head/><body><p><span style=\" font-size:48pt; font-weight:700; color:#ffffff;\">MENU</span></p></body></html>"))
        self.background_label.setText(_translate("MenuWindow", "<html><head/><body><p><img src=\":/newPrefix/EUROAVIA_Logo.png\"/></p></body></html>"))
        self.pushButton.setText(_translate("MenuWindow", "Application Form"))
        self.woman_choosing_label.setText(_translate("MenuWindow", "<html><head/><body><p><img src=\":/newPrefix/pngtree-woman-making-decision-between-two-options-png-image_6336529.png\"/></p></body></html>"))
        self.pushButton_2.setText(_translate("MenuWindow", "Login"))

        qpixmap = QPixmap("images/EUROAVIA_Logo.png")
        self.background_label.setPixmap(qpixmap)
        qpixmap = QPixmap("images/pngtree-woman-making-decision-between-two-options-png-image_6336529.png")
        self.woman_choosing_label.setPixmap(qpixmap)
        qpixmap = QPixmap("images/EUROAVIA_Logo.png")
        self.euroavia_logo_label.setPixmap(qpixmap)
        qpixmap = QPixmap("images/image-removebg-preview.png")
        self.plane_label.setPixmap(qpixmap)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MenuWindow = QtWidgets.QMainWindow()
    ui = Ui_MenuWindow()
    ui.setupUi(MenuWindow)
    MenuWindow.show()
    sys.exit(app.exec())
